name: GitHub Auto Release
on: workflow_dispatch
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 11
          distribution: corretto
